### PR TITLE
Update peer dependencies to include Angular 5

### PR DESCRIPTION
**Pull request by ercultimate**
From what I have seen in our application, there are no issues using this with Angular 5.

### CODE REVIEW

**Comment by NoMercy235** [comment]
Can we please merge this, so we don't have to make a new repository ourselves?

**Comment by NoMercy235** [comment]
Thank you!

**Comment by NoMercy235** [comment]
One more thing, though. Could you also publish a new npm version?

**Comment by NicholasAzar** [comment]
@NoMercy235 1.1.2

**Pull request merged**
